Repository ps-thunderatz/sumo_controller, pull requests merged in 2021-09, with the labels that each got.

#13 Feature/gitignore
  .gitignore
Labels: enhancement

#15 🐛 Fix bugs
  .github/workflows/lint.yml
  README.md
  launch/example.launch
  launch/sumo_controller.launch
  src/example_node.py
  src/sumo_controller_node.py
  src/utils/__init__.py
  src/utils/distance_sensor.py
  src/utils/imu_sensor.py
  src/utils/line_sensor.py
  src/utils/match_state.py
  src/utils/motors.py
Labels: bug, documentation

#16 🤼 Sumô Controller 🤖
  .github/workflows/lint.yml
  .gitignore
  .vscode/settings.json
  CMakeLists.txt
  LICENSE
  README.md
  config/line_sensor_param.yaml
  launch/example.launch
  launch/sumo_controller.launch
  package.xml
  src/example_node.py
  src/sumo_controller_node.py
  src/utils/__init__.py
  src/utils/distance_sensor.py
  src/utils/imu_sensor.py
  src/utils/line_sensor.py
  src/utils/match_state.py
  src/utils/motors.py
Labels: documentation, enhancement
